defaults: &defaults
  host: localhost
  # default port : 27017
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

# 1.9.2-p136 and https://github.com/tenderlove/psych/issues#issue/8
# ha, I killed my development database !!!
development:
  host: localhost
  database: conference_on_rails_development

cucumber:
  host: localhost
  database: conference_on_rails_test

test:
  host: localhost
  database: conference_on_rails_test

# set these environment variables on your prod server
production:
  <% if ENV['MONGOHQ_URL'] %>
  uri: <%= ENV['MONGOHQ_URL'] %>
  <% else %>
  host: localhost
  database: conference-on-rails-production
  <% end %>